using Lesson13;

HashMap<string, int> _hashMap = new HashMap<string, int>(10);
Console.WriteLine($"Capacity: {_hashMap.Capacity}");
_hashMap["cat"] = 5;
_hashMap["dog"] = 5;
_hashMap["cat"] = 10;
Console.WriteLine($"Contains cat: {_hashMap.ContainsKey("cat")}");
Console.WriteLine($"cat = {_hashMap["cat"]}");
_hashMap["car"] = 15;
_hashMap["yellow"] = 65;
_hashMap["blue"] = 78;
Console.WriteLine($"yellow = {_hashMap["yellow"]}");
Console.WriteLine($"blue = {_hashMap["blue"]}");
_hashMap.Remove("ddd");
_hashMap.Remove("car");
Console.WriteLine($"Contains car: {_hashMap.ContainsKey("car")}");
_hashMap["cat2"] = 25;
_hashMap["cat3"] = 35;
_hashMap["cat4"] = 45;
_hashMap["cat5"] = 55;
_hashMap["cat6"] = 65;
_hashMap["cat7"] = 75;
_hashMap["cat8"] = 85;
_hashMap["cat9"] = 95;
_hashMap["cat9"] = 105;
Console.WriteLine($"cat = {_hashMap["cat"]}");
Console.WriteLine($"yellow = {_hashMap["yellow"]}");
Console.WriteLine($"blue = {_hashMap["blue"]}");
Console.WriteLine($"Capacity: {_hashMap.Capacity}");
Console.ReadKey();